version: "3.3"

services:
  simplerest:
     build: .
     command: python main.py
     ports:
      - 8090:8080
     depends_on:
       - timeScaledb

  grafana:
    container_name: grafana
    image: grafana/grafana:6.5.0
    ports:
      - "3000:3000"

  timeScaledb:
    container_name: timeScaledb 
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/timescale/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cdlmint
      - POSTGRES_DB=cdl-mint

  # web:
  #       build: .
  #       command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  #       volumes:
  #         - .:/code
  #       ports:
  #         - "8000:8000"
  #       depends_on:
  #         - timeScaledb
  
  pgadmin:
            container_name: pgadmin
            image: dpage/pgadmin4
            environment:
              - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
              - PGADMIN_DEFAULT_PASSWORD=admin
            ports:
              - "5050:80"
            depends_on:
              - timeScaledb

volumes:
  postgres_data: